apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gravitee-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: gravitee.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: gravitee-api
            port:
              number: 8083
      - path: /ui
        pathType: Prefix
        backend:
          service:
            name: gravitee-ui
            port:
              number: 80
      - path: /gateway
        pathType: Prefix
        backend:
          service:
            name: gravitee-gateway
            port:
              number: 8082
      - path: /portal
        pathType: Prefix
        backend:
          service:
            name: gravitee-portal
            port:
              number: 8084
