apiVersion: batch/v1
kind: Job
metadata:
  name: couchdb-init
spec:
  template:
    spec:
      containers:
      - name: curl
        image: curlimages/curl:latest
        env:
        - name: COUCHDB_USER
          valueFrom:
            secretKeyRef:
              name: couchdb-secret
              key: username
        - name: COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: couchdb-secret
              key: password
        command: ["/bin/sh", "-c"]
        args:
          - |
            until curl -u "$COUCHDB_USER:$COUCHDB_PASSWORD" -s -X PUT http://couchdb:5984/_users; do
              echo "Waiting for CouchDB to be ready..."
              sleep 5
            done;
            curl -u "$COUCHDB_USER:$COUCHDB_PASSWORD" -X PUT http://couchdb:5984/_replicator;
            curl -u "$COUCHDB_USER:$COUCHDB_PASSWORD" -X PUT http://couchdb:5984/_global_changes;
      restartPolicy: OnFailure
