apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reactjs-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: reactjs.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: reactjs
            port:
              number: 80
